"""
Each new term in the Fibonacci sequence is generated by 
adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …

By considering the terms in the Fibonacci sequence whose values 
do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci_sequence():
    f0 = 0
    f1 = 1
    fib = [f0, f1]
    while True:
        if fib[f0] + fib[f1] > 4000000: break
        fib.append(fib[f0] + fib[f1])
        f0 += 1
        f1 += 1
    return fib

def even_sum():
    filtered_fib = [ i for i in fibonacci_sequence() if i % 2 == 0 ]
    result = sum(filtered_fib)
    return f'Sum: {result:,d}'
    
